name: flatbread
dependencies:
  - python >= 3.7
  # build
  - mypy
  - flake8
  - setuptools
  - wheel
  - twine
  # jupyter
  - jupyter
  - jupyterlab
  - ipykernel
  # data
  - pandas
  - openpyxl
  # visualization
  - matplotlib
